# Generated by Django 6.1 on 2026-09-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(default='employer@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
